sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t evandam93/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true evandam93/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-1-096007086684"
  bucket_path: "docker-react"
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
  on:
    branch: master