sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t evandam93/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true evandam93/docker-react npm run test